### ISSUE TITLE
EU-DSGVO

### ISSUE THREAD

**Issue by utetrapp** [geli-lms/geli#755]
# User Story

## Acceptance criteria:
- [x] accept storage of personal data
- [x] decline storage of personal data
- [x] #776 inform user of stored data
- [x] #775 delete personal data
- [x] #565 cookie information
- [x] #768 impressum
- [x] #550 terms of use
- [x] #778 add checkbox for accepting privacy declaration
- [x] Registration checkbox accept terms of use
(- [ ] GoogleOptOut or GoogleOptOut hint in disclaimer)

**Comment by d89** [comment]
The last few weeks, we were pretty busy ensuring the DSGVO-readyness for Incloud. In this process, we created a whitepaper for our clients that summarizes what needs to be done in order to get their web applications DSGVO compliant: https://www.incloud.de/files/EU-DSGVO-Whitepaper.pdf

In a nutshell:

- Easily understandable privacy policy.
- Possibility to export all the personal data, that GELI has saved for my account.
- Possibility to fully delete my own account.
- Anonymization of all the personal user data, that is not needed in order to operate the platform. Maybe IP addresses that are sent to Google Analytics?
- Regular security updates of all the used libraries and of the operation system itself to ensure the system is as "hacking proof" as possible.
