### ISSUE TITLE
Comprehensive search for remaining legacy security flaws

### ISSUE THREAD

**Issue by torss** [geli-lms/geli#853]
# User Story

### As a: 

developer

### I want:

to know whether there are any remaining legacy security flaws or not

### so that:

any remaining flaws can be fixed (thus closing #748) and `geli` can be declared as (probably) secure.

## Acceptance criteria:

- [x] Audit `AboutController`.
- [x] Audit `APIInfoController`.
- [x] Audit `AuthController`.
- [x] Audit `ChatRoomController`.
- [x] Audit `ConfigController`.
- [x] Audit `CourseController`. **[Re-Audit]** 
- [x] Audit `DownloadController`.
- [x] Audit `DuplicationController`.
- [x] Audit `ExportController`.
- [x] Audit `ImportController`.
- [x] Audit `LectureController`.
- [x] Audit `MediaController`.
- [x] Audit `MessageController`.
- [x] Audit `NotificationController`.
- [x] Audit `NotificationSettingsController`.
- [x] Audit `ProgressController`.
- [x] Audit `ReportController`.
- [x] Audit `UnitController`.
- [x] Audit `UserController`. **[Re-Audit]**
- [x] Audit `WhitelistController`.
- [x] Audit `ChatServer`.
- [x] Audit static `uploads` route. **[Re-Audit]**

## Legend:

**[Re-Audit]**: This has already been secured before this issue was created, but should be audited again just to be sure that nothing was missed.

Process:
⚙️: Audit still officially in progress.

Security:
🔒❌: Vulnerability present!
🔒❓: Security uncertain _(could be irrelevant or a non-security bug)_.
🔒✔️: Seems to be secure _(assuming proper server configuration)_.
🔒🛠️: Like 🔒✔️, but there was some issue that has been fixed _(during the course of this audit)_.

Non-security bugs _(any bug that doesn't affect security)_:
🐛❌: Unresolved non-security bug present.
🐛❓: Might have a non-security bug, but could be irrelevant.
🐛🛠️: Has been fixed _(during the course of this audit)_.

Refactoring _(independent of security, omitted if no issue was found)_.:
📝❕: Should be refactored.
📝❔: Could maybe use some minor refactoring.
📝🛠️: Has been refactored _(during the course of this audit)_.

## Additional info:

This issue has now been promoted to be a `tracking` issue for the found problems.
Tracked issues relating to security will also be tracked by #748.

Controllers that currently still have 🔒❌ are: **None!**
Which is why this tracking issue will be closed for now by PR #1197. Feel free to reopen it in the future, e.g. when working on the other known issues listed herein.

## Estimate:
20h for the initial audits

**Comment by torss** [comment]
🔒✔️ `AboutController`:
Has only a single simple `{get} /api/about/dependencies` route that responds with the contents of `nlf-licenses.json` to any public request. Should be safe _(as long as no protected information is ever included)_.

**Comment by torss** [comment]
🔒✔️ `APIInfoController`:
Has only a single simple `{get} /api/` route that responds with basically static `APIInfo` data to any public request. `APIInfo` doesn't appear to leak any strictly critical information. It does however contain the `config.teacherMailRegex`, which could hypothetically help an attacker if the regex isn't written properly. This regex is also used in the front-end to immediately check the validity of an email address for teacher registration client-side. Since this isn't by itself a vulnerability - it would only allow an attacker to directly see a vulnerable regex - I will mark this as secure.

**Comment by torss** [comment]
### ⚙️ `AuthController`

🔒✔️ 📝❓ `{post} /api/auth/login`:

This and the `passportLoginStrategy` (`LocalStrategy`) seems to be secure.
`passportLoginStrategy` could perhaps use some minor refactoring by introducing "proper" error codes (and put them in `errorCodes.ts` instead of local strings).

Also, the route itself will soon(-ishly) be slightly simplified in #849 _(after release 0.8 is finally complete)_ by eliminating the `mediaToken`s completely.

**Comment by torss** [comment]
### 🔒❓ 📝❔ `ChatRoomController`

* 🔒❓ Has only a single simple `{get} /api/chatRoom` route that responds with a `ChatRoom` to any logged-in user. It doesn't call `toObject` on the `ChatRoom`, so it leaks information! _(However, this might only be a non-security bug.)_
* 📝❔ Could perhaps use some minor refactoring by introducing "proper" error codes (in `errorCodes.ts` instead of a local string).

**Comment by torss** [comment]
### ⚙️ `ConfigController`

🔒✔️ 🐛❓ 📝❔ `{get} /api/config/public/:id`:

* 🔒✔️ Seems to be secure,
* 📝❔ but could use some minor refactoring
  (invert the outer `if`; `try/catch` probably can be removed; `UnauthorizedError` doesn't need to receive an empty string),
* 🐛❓ and the `publicConfig` method (or rather the `publicConfigs` `RegExp`s) probably should match exactly (instead of just substrings). Or it might be even better to just add a `isPublic`-flag or something to the `Config` model (thus eliminating the need for the hard-coded `publicConfigs`; although their public requests in the front-end would still be hard-coded, so maybe this wouldn't really be beneficial, unless we use the `Config` model for arbitray admin-definable stuff I guess).

**Comment by torss** [comment]
### ⚙️ 📝❕  `CourseController`:

📝❕ `uploadOptions` is unused, can likely be removed.
📝❕ _(Combination of multiple small minor refactoring issues below.)_

🔒✔️ 📝❔ `{get} /api/courses/`:

* 🔒✔️ Seems to be secure; only returns safe dashboard-specific course data anyway.
* 📝❔ There is a double whitespace that could be removed.

🔒✔️ `{get} /api/courses/:id`:

Seems to be secure.

🔒✔️ 📝❔ `{get} /api/courses/:id/edit`:

* 🔒✔️ Seems to be secure
* 📝❔ Shares the initiating functionality with `{get} /api/courses/:id` which could be factored out, but it is only a couple of lines anyway.
* 📝❔ Side note: The `"units"`, their `"unitCreator"` and the `"courseAdmin"` (i.e. `Unit`s and `User`s) seem to contain their ids twice (as `"_id"` and `"id"`); this probably has no purpose and could be refactored.

🔒✔️ 📝❔ `{post} /api/courses/`:

* 🔒✔️ Seems to be secure, assuming `new Course(course)` isn't vulnerable somehow.
* 📝❔ `request` parameter is unused.
* 📝❔ The route responds with the newly created course via `newCourse.toObject()`; perhaps it would be better to only acknowledge the creation _(e.g. via an empty object as response)_ and leave the data retrieval to the `{get}` routes _(the latter of which might functionally be the case already anyway)_.

🔒❓ `{post} /api/courses/mail`:

If an attacker had access to a `teacher` account this route could be abused to send emails to completely random (non-student / non-`geli`-user) addresses. This is in contradiction to the purpose stated in the route's documentation - "`Send mail to selected users`". Thus it might be sensible to restrict the functionality of this route, e.g. so that it can only send to other registered users via their ids.

🔒✔️ 🐛❓ 📝❔ `{post} /api/courses/:id/enroll`:

* 🔒✔️ Seems to be secure.
* 🐛❓ Is the `course.students.indexOf(currentUser._id) < 0` condition is broken, because `course.students` is of type `IUser[]` and objects would always fail the comparison with the `currentUser._id`, or does that work via `mongoose` functionality?
* 📝❔ One could slightly improve the efficiency by replacing the `wUsers.filter[...]` condition with e.g. `wUsers.some[...]`.

⚙️ 📝❔ `{post} /api/courses/:id/leave`:

* 📝❔ `data` parameter is unused.

**Comment by torss** [comment]
From here on I might focus less on finding/documenting non-security issues.

**Comment by torss** [comment]
### 🔒❓ 🐛❓ 📝❕  `CourseController`

* 📝❔ Unused imports `FreeTextUnit, CodeKataUnit, TaskUnit`.

📝❔ `cleanupCache`:

* 📝❔ Unnecessary whitespace in `fs.unlink( config.tmpFileCacheFolder`.
* 📝❔ Maybe possible to refactor this using `async`/`await`.

🔒✔️ `{get} /api/download/:id`: 

Seems to be secure, as long as the IDs can't be guessed.

🔒❓ 🐛❓ 📝❕ `{post} /api/download/pdf/individual`:

* 🔒❓ Any user could spam countless different course PDF download configurations; maybe there should be a time-based download limit for a certain number of requests?
* 🐛❓ `createFileHash` uses the "broken" `sha1` _(probably irrelevant here)_.
* 📝❕ Negate condition of the large `if`-block.
* 📝❔ Could be refactored to use `checkPrivileges` to check permissions.

🔒❓ 🐛❓ 📝❕ `{post} /api/download/pdf/single`:

* 🔒❓ 🐛❓ 📝❕  _(Same as `{post} /api/download/pdf/individual`.)_
* 📝❔ Maybe code shared with `{post} /api/download/pdf/individual` could be factored out.

✔️ `{delete} /api/download/`:

Seems to be secure; only allows `admin` access anyway.

**Comment by torss** [comment]
### ⚙️ `DuplicationController`

🔒❌ 🐛❓ 📝❔ `{post} /api/duplicate/course/:id`:

* 🔒❌ The route doesn't check that the request comes from a user that is actually allowed to edit the course, so a malicious `teacher` _(or `admin` of course)_ could gain access to any course by duplicating it _(setting himself as course admin and/or simply by looking at the response, which returns the whole duplicated course)_.
* 🐛❓ Only applies `delete exportedCourse.students`, is this sufficient? _A whitelist-approach would be better to future-proof security anyway._
* 📝❔ As already noted in a local comment, the `@CurrentUser` could/should be used instead of passing the `courseAdmin` via `@Body() data`.
* 📝❔ `request` parameter is unused.
* 📝❔ The `InternalServerError` message doesn't use the `errorCodes` file.

**Comment by torss** [comment]
### 🔒❌ `ExportController`

🔒❌ `{get} /api/export/course/:id`:

The route doesn't check that the request comes from a user that is actually allowed to edit the course.

🔒❌ `{get} /api/export/lecture/:id`:

_(Same issue as in `{get} /api/export/course/:id`.)_

🔒❌ `{get} /api/export/unit/:id`:

_(Same issue as in `{get} /api/export/course/:id`.)_

🔒✔️ `{get} /api/export/user`:

Seems to be secure.

**Comment by torss** [comment]
### 🔒❌ 📝❕ `LectureController`

📝❔ Unused `Notification` import.

_All 4 routes `{get} /api/lecture/:id`, `{post} /api/lecture/`, `{put} /api/lecture/:id`, `{delete} /api/lecture/:id`:_

* 🔒❌ Don't check that the user is allowed to view/edit the associated course.
* 📝❕ Should use `async`/`await`.

**Comment by torss** [comment]
### ⚙️ `MediaController`

📝❕ None of the routes are documented.

**Comment by torss** [comment]
### 🔒❌ 📝❕ `NotificationController`

📝❔ Various unused imports.

🔒❌ 📝❔ `{post} /api/notification/`:

* 🔒❌ The route doesn't check that the requesting user actually has access to the associated course. Thus a `teacher`-level attacker would be capable of doing harm via misinformation; e.g. by sending notifications to students of other courses with text that includes a malicious link _(that students might follow, believing it was sent by their actual teacher for some reason)_. Note that notifications might also be sent as email to some students, exacerbating this problem.
* 📝❔ Unused `request` parameter.
* 📝❔ `BadRequestError` message doesn't use `errorCodes`.
* 📝❔ Unnecessary `notified: true` in success response.

🔒❌ 📝❔ `{post} /api/notification/user/:id`:

_(Same issues as `{post} /api/notification/`.)_

🔒❌ `{get} /api/notification/user/:id`:

Doesn't check that the notifications actually belong to the given user ID.
Should probably be changed to just use the `@CurrentUser`.

🔒✔️ 📝❕ `{delete} /api/notification/:id`:

Seems to be secure, but should probably better just return an empty object as success response.

**Comment by torss** [comment]
### 🔒❌ `NotificationSettingsController`

* 🔒❌ The `NotificationSettings` `toObject` utilized in the routes isn't sanitizing the data, thus directly leaking course and user data!
* 🔒❌ _(Not secure because of a leaking `NotificationSettings` `toObject`.)_
* 📝❔ Many object properties are unnecessarily quoted.

🔒❌ `{get} /api/notificationSettings/user/:id`:

Doesn't check whether the `@CurrentUser` is actually authorized to obtain the notification settings for the given arbitrary user ID. The route should probably be changed to just use the `@CurrentUser`.

🔒❌ 📝❕ `{put} /api/notificationSettings/user/:id`:

* 🔒❌ Doesn't check that the notification settings ID actually belongs to the `@CurrentUser`, thus any user could override someone else's settings.
* 🔒❌ _(Not secure because of a leaking `NotificationSettings` `toObject`.)_
* 📝❔ `BadRequestError` message doesn't use `errorCodes`.
* 📝❕ Should probably return an empty object as success response instead of `settings.toObject()`.
  
🔒❌ 📝❔ `{post} /api/notificationSettings/`:

* 🔒❌ _(Not secure because of a leaking `NotificationSettings` `toObject`.)_
* 📝❔ The role of this function could be fulfilled by _(fusing it with)_ `{put} /api/notificationSettings/user/:id`.
* 📝❔ `BadRequestError` message doesn't use `errorCodes`.

**Comment by torss** [comment]
### 🔒❌ 📝❕ `ProgressController`

* 🔒✔️ The `Progress` schema's `toObject` transform seems to be secure. _(Although a whitelist approach might be better to ensure security under future changes and to automatically eliminate unneeded `mongoose` metadata.)_
* 📝❔ Doesn't use the `errorCodes` file for exception messages.

🔒❌ 📝❕ `{get} /api/progress/units/:id` & `{get} /api/progress/courses/:id ` & `{get} /api/progress/users/:id`:

* 🔒❌ Doesn't seem to check the user authorization sufficiently.
* 📝❕ The shared functionality should be factored out.

🔒❓ `{post} /api/progress/`:

* 🔒❓ Doesn't check that the user is authorized for the course, but the attack damage potential appears to be low, so this isn't critical.
* 📝❔ The `currentUser?: IUser` type likely isn't actually optional.

🔒❓ `{put} /api/progress/:id`:

_(Situation similar to `{post} /api/progress/`.)_

**Comment by torss** [comment]
### `ReportController`

* 📝❔ It's seems possible to factor out more shared functionality between all 4 routes.
* 🐛❓ The routes seem to respond with more data than necessary. This could be dealt with by means of a whitelist-like approach (as done e.g. by `ICourseModel`'s `forView` or `forDashboard`), which would also ensure security more effectively under e.g. future model property additions. _(Unimportant side note: Currently `hasAccessKey` is always `false` since that property is set in the `course`'s `toObject` method depending on the existence of `accessKey`, which  (rightfully) isn't attached in these routes.)_

`{get} /api/report/overview/courses/:id` &
`{get} /api/report/result/courses/:id` &
`{get} /api/report/details/courses/:courseId/units/:unitId`:

* 🔒✔️ Seems to be secure via `@Authorized(['teacher', 'admin'])` and `checkAccess`.
* 📝❔ The `checkAccess` controller method could be refactored to use the `ICourseModel`'s `checkPrivileges` method.

`{get} /api/report/overview/users/:id`:

* 🔒✔️ Seems to be secure via `id !== currentUser._id.toString()`...
* 📝❕ ...but the route probably should just take the `@CurrentUser()`, without the superfluous `@Param('id')`. _(Why bother passing an id if it has to be the `@CurrentUser()` anyway?)_

**Comment by torss** [comment]
### `UnitController`

* 📝❔ Unused `ValidationError` import.

`{get} /api/units/:id`:

* 🔒❌ Doesn't check for `@CurrentUser` authorization.
  _(Likely not critical since the unit ID must be known.)_
* 📝❔ The `unit` response sanitation could perhaps be slightly improved.

`{post} /api/units/` &
`{put} /api/units/:id` &
`{delete} /api/units/:id`:

* 🔒❌ Doesn't check for `@CurrentUser` authorization beyond `@Authorized(['teacher', 'admin'])`, so a `teacher`-level attacker could maliciously add / update / delete units to / of any course.
* 📝❕ Should probably better just return an empty object as success response.

`{post} /api/units/`:

* 📝❔ `checkPostParam`'s `BadRequestError`'s don't use the `errorCodes`.
* 📝❔ `checkPostParam` is only used in this one route and could just be inserted there.

**Comment by torss** [comment]
### `UserController`

* 📝❔ Unused `IUserModel` import.

`{get} /api/users/`:

* 🔒✔️ Seems to be secure due to `user.forUser` (and `@Authorized(['teacher', 'admin'])`).

`{get} /api/users/members/search`:

* 🔒✔️ Seems to be secure due to `user.forUser`.

`{get} /api/users/roles/`:

* 🔒✔️ Seems to be secure due to `@Authorized(['admin'])` & safe, static content.

`{get} /api/users/:id`:

* 🔒✔️ Seems to be secure due to `user.forUser`.
* 📝❔ The `currentUser?: IUser` type isn't actually optional.

`{post} /api/users/picture/:id`:

* 🔒❓ Seems to be mostly secure _(due to `mimetype` check, `user.checkEditableBy`, `user.forUser`)_, but it doesn't appear to set a size maximum for the upload, which might be sensible.
* 📝❔ One `ForbiddenError` doesn't use `errorCodes`.
* 📝❕ Should probably better just return an empty object as success response.

`{put} /api/users/:id`:

* 🔒✔️ Seems to be secure due to various checks _(including `oldUser.checkEditableBy`, `oldUser.isValidPassword` and `updatedUser.forUser`)_.
* 📝❕ Should probably better just return an empty object as success response.

`{delete} /api/users/:id`:

* 🔒✔️ Seems to be secure due to various checks that only allow `admin`s to actually delete users
  _(while requests from others will only send an email to a random `admin`)_.
* 📝❔ Unnecessarily returns a non-empty object with `result: true`.

**Comment by torss** [comment]
### `WhitelistController`

* 📝❔ 4 unused imports.
* 📝❔ Unused `uploadOptions`.
* 📝❕ The name of the `toMongooseObjectId` controller method might be misleading _(it doesn't convert the `whitelistUser` input to a mongoose object ID; instead it creates a new object with data from the given `whitelistUser` and converts the `courseId` via `new ObjectId`)_.

`{get} /api/whitelist/check/:whitelist`:

* 🔒✔️ Seems to be secure due to `@Authorized(['teacher', 'admin'])` and rather safe content.
* 📝❔ Unused `data` and `currentUser` parameters.

`{get} /api/whitelist/:id`:

* 🔒❌ Doesn't check for `@CurrentUser` authorization
  and also lacks `@Authorized(['teacher', 'admin'])`.
* 📝❕ Should use `async`/`await`.

`{post} /api/whitelist/` &
`{put} /api/whitelist/:id` &
`{delete} /api/whitelist/:id`:

* 🔒❌ Doesn't check for `@CurrentUser` course authorization.
* 📝❕ Should probably better just return an empty object as success response.

**Comment by torss** [comment]
### `ChatServer`

* 🔒❌ While the common JWT is verified, the actual messages aren't checked, so that e.g. impersonation appears to be possible! To fix this the user id contained in the JWT should be utilized for various checks.
* 📝❔ The `if`-branches in the `jwt.verify` callback could be refactored to eliminate one branch.

**Comment by torss** [comment]
### `/api/uploads` (static `uploads` route)

* 🔒❓ While this route is secured via the (now cookie-transferred) JWTs by using `passportJwtMiddleware`, this only ensures that users have to be logged in to access files.
  I.e. it does not check individual user authorization. This is perhaps not critical since the randomized file names need to be known first, but should be fixed eventually. There was an attempt in #807 to deal with this issue by introducing a new `UploadsController`, but that caused problems with video file access (see point "No differentiation between different \[...\]" under "Known Issues" in PR #807).
